import { useMemo,useState } from 'react';
import './category-manager.css';

const API='http://localhost:5000';
const slugify=value=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const departmentOf=item=>item.department||(item.type==='paties'?'pastries':'cakes');
function Switch({value,onChange,label}){return <button type="button" role="switch" aria-checked={value} aria-label={label} className={`category-switch ${value?'on':''}`} onClick={()=>onChange(!value)}><span/></button>}

export default function CategoryManager({items,mainCategories=[],patch,create,remove,createMain,patchMain,removeMain}){
 const [tab,setTab]=useState('main'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[form,setForm]=useState(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const mainBySlug=new Map(mainCategories.map(x=>[x.slug,x]));
 const shownMain=useMemo(()=>mainCategories.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())),[mainCategories,query]);
 const shownSubs=useMemo(()=>items.filter(x=>(filter==='all'||departmentOf(x)===filter)&&x.name.toLowerCase().includes(query.toLowerCase())),[items,query,filter]);
 const open=(kind,item={})=>{setForm({kind,item});setError('')},close=()=>{setForm(null);setError('')};
 async function saveMain(e){e.preventDefault();setSaving(true);setError('');try{const f=new FormData(e.currentTarget),name=f.get('name').trim(),body={name,slug:form.item.slug||slugify(name),productType:form.item.productType||'cakes',order:+f.get('order'),showInTopNavigation:f.get('showInTopNavigation')==='on',showInCategoryBar:f.get('showInCategoryBar')==='on',showInHomeFavourite:f.get('showInHomeFavourite')==='on',isActive:f.get('isActive')==='on'};form.item._id?await patchMain(form.item._id,body):await createMain(body);close()}catch(err){setError(err.message)}finally{setSaving(false)}}
 async function saveSub(e){e.preventDefault();setSaving(true);setError('');try{const f=new FormData(e.currentTarget),name=f.get('name').trim(),department=f.get('department');let image=form.item.image||'';const file=f.get('image');if(file?.size){const upload=new FormData();upload.append('image',file);upload.append('department',department);const response=await fetch(`${API}/api/categories/upload-image`,{method:'POST',headers:{Authorization:`Bearer ${localStorage.getItem('mnb_admin_token')}`},body:upload}),data=await response.json();if(!response.ok)throw new Error(data.message||'Image upload failed');image=data.image}const body={name,slug:form.item.slug||slugify(name),department,image,description:f.get('description'),showInHomeFavourite:f.get('showInHomeFavourite')==='on',isActive:f.get('isActive')==='on'};form.item._id?await patch(form.item._id,body):await create(body);close()}catch(err){setError(err.message)}finally{setSaving(false)}}
 async function destroy(item,kind){if(!window.confirm(`Delete “${item.name}”?`))return;try{setError('');kind==='main'?await removeMain(item._id):await remove(item._id)}catch(err){setError(err.message)}}
 return <section className={`category-manager ${tab==='sub'?'showing-subcategories':''}`}>
  <div className="category-heading"><div><p>CATALOG MANAGEMENT</p><h2>{tab==='main'?'Main Categories':'Subcategories'} <span>{tab==='main'?mainCategories.length:items.length}</span></h2></div><button onClick={()=>open(tab,{})}>Add {tab==='main'?'Main Category':'Subcategory'}</button></div>
  {form?.kind==='main'&&<form className="category-form" onSubmit={saveMain}><div className="category-form-title"><div><p>MAIN CATEGORY</p><h3>{form.item._id?'Edit main category':'Add main category'}</h3></div></div><label>Name<input name="name" required defaultValue={form.item.name||''}/></label><label>Display order<input name="order" type="number" min="0" defaultValue={form.item.order||0}/></label><div className="category-checks"><label><input name="showInTopNavigation" type="checkbox" defaultChecked={form.item.showInTopNavigation!==false}/> Top navigation</label><label><input name="showInCategoryBar" type="checkbox" defaultChecked={form.item.showInCategoryBar!==false}/> Category bar</label><label><input name="showInHomeFavourite" type="checkbox" defaultChecked={form.item.showInHomeFavourite!==false}/> Home favourite</label><label><input name="isActive" type="checkbox" defaultChecked={form.item.isActive!==false}/> Active</label></div><div className="category-form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button disabled={saving}>{saving?'Saving…':'Save Main Category'}</button></div></form>}
  {form?.kind==='sub'&&<form className="category-form" onSubmit={saveSub}><div className="category-form-title"><div><p>SUBCATEGORY</p><h3>{form.item._id?'Edit subcategory':'Add subcategory'}</h3></div></div><label>Main category<select name="department" required defaultValue={departmentOf(form.item)}>{mainCategories.filter(x=>x.isActive!==false).map(x=><option key={x._id} value={x.slug}>{x.name}</option>)}</select></label><label>Subcategory name<input name="name" required defaultValue={form.item.name||''}/></label><label>Cloudinary image<input name="image" type="file" accept="image/*"/></label><label className="wide">Description<input name="description" defaultValue={form.item.description||''}/></label><div className="category-checks"><label><input name="showInHomeFavourite" type="checkbox" defaultChecked={form.item.showInHomeFavourite!==false}/> Home favourite</label><label><input name="isActive" type="checkbox" defaultChecked={form.item.isActive!==false}/> Active</label></div>{form.item.image&&<img className="category-form-preview" src={form.item.image} alt=""/>}<div className="category-form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button disabled={saving}>{saving?'Saving…':'Save Subcategory'}</button></div></form>}
  <div className="category-toolbar"><div className="category-tabs"><button className={tab==='main'?'active':''} onClick={()=>{setTab('main');setForm(null);setQuery('')}}>Main Categories</button><button className={tab==='sub'?'active':''} onClick={()=>{setTab('sub');setForm(null);setQuery('')}}>Subcategories</button></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${tab==='main'?'main categories':'subcategories'}…`}/>{tab==='sub'&&<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All main categories</option>{mainCategories.map(x=><option key={x._id} value={x.slug}>{x.name}</option>)}</select>}</div>
  {error&&<p className="category-error">{error}</p>}
  <div className="table-wrap">{tab==='main'?<table><thead><tr><th>Main Category</th><th>Subcategories</th><th>Products</th><th>Order</th><th>Top Navigation</th><th>Category Bar</th><th>Home Favourite</th><th>Status</th><th>Actions</th></tr></thead><tbody>{shownMain.map(x=>{const locked=(x.subcategoryCount||0)+(x.productCount||0)>0;return <tr key={x._id}><td><b>{x.name}</b></td><td><b>{x.subcategoryCount||0}</b></td><td><b>{x.productCount||0}</b></td><td><input className="category-order" type="number" min="0" defaultValue={x.order||0} onBlur={e=>patchMain(x._id,{order:+e.target.value})}/></td><td><Switch value={x.showInTopNavigation!==false} label={`${x.name} top navigation`} onChange={v=>patchMain(x._id,{showInTopNavigation:v})}/></td><td><Switch value={x.showInCategoryBar!==false} label={`${x.name} category bar`} onChange={v=>patchMain(x._id,{showInCategoryBar:v})}/></td><td><Switch value={x.showInHomeFavourite!==false} label={`${x.name} home favourite`} onChange={v=>patchMain(x._id,{showInHomeFavourite:v})}/></td><td><Switch value={x.isActive!==false} label={`${x.name} active`} onChange={v=>patchMain(x._id,{isActive:v})}/></td><td><div className="category-actions"><button onClick={()=>open('main',x)}>Edit</button><button className="danger" disabled={locked} title={locked?'Move subcategories and products before deleting':''} onClick={()=>destroy(x,'main')}>Delete</button></div></td></tr>})}</tbody></table>:<table><thead><tr><th>Image</th><th>Subcategory</th><th>Main Category</th><th>Products</th><th>Order</th><th>Home Favourite</th><th>Status</th><th>Actions</th></tr></thead><tbody>{shownSubs.map(x=><tr key={x._id}><td>{x.image?<img className="category-thumb" src={x.image} alt=""/>:<span className="category-thumb empty">No image</span>}</td><td><b>{x.name}</b><small>{x.description}</small></td><td><span className="category-department">{mainBySlug.get(departmentOf(x))?.name||departmentOf(x)}</span></td><td><b>{x.productCount||0}</b></td><td><input className="category-order" type="number" min="0" defaultValue={x.order||0} onBlur={e=>patch(x._id,{order:+e.target.value})}/></td><td><Switch value={x.showInHomeFavourite!==false} label={`${x.name} home favourite`} onChange={v=>patch(x._id,{showInHomeFavourite:v})}/></td><td><Switch value={x.isActive!==false} label={`${x.name} active`} onChange={v=>patch(x._id,{isActive:v})}/></td><td><div className="category-actions"><button onClick={()=>open('sub',x)}>Edit</button><button className="danger" disabled={x.productCount>0} title={x.productCount>0?'Move products before deleting':''} onClick={()=>destroy(x,'sub')}>Delete</button></div></td></tr>)}</tbody></table>}</div>
  {!(tab==='main'?shownMain:shownSubs).length&&<div className="category-empty">No matching categories found.</div>}
 </section>
}
