import { Image, LoaderCircle } from 'lucide-react';
import { useEffect, useState } from 'react';

const API='http://localhost:5000/api';
const defaults={heroEyebrow:'MY NEW BAKERY',heroTitle:'Our story',heroDescription:'We bake thoughtful cakes and golden little bites for the moments you will remember.',heroImage:'/images/cakes/wedding-hero.png',storyKicker:'OUR STORY',storyTitle:'Baked with passion, served with love.',storyText:'',storyExtra:'Every cake is made with carefully selected ingredients, skilled hands and attention to the smallest details.',storyImage:'/images/cakes/Header.jfif',storyImageLabel:'My New Bakery',reasonsKicker:'WHY CHOOSE US',reasonsTitle:'What makes us special?',creationKicker:'OUR CREATIONS',creationTitle:'Made to make you smile.',creationButton:'View our products',numbersKicker:'OUR NUMBERS',numbersTitle:'Serving happiness every day',stats:[{value:'500+',label:'Cakes delivered'},{value:'1000+',label:'Happy customers'},{value:'50+',label:'Custom cakes'},{value:'5+',label:'Years of experience'}]};
const reasonDefaults=[['Fresh ingredients','Premium ingredients selected fresh for everything we bake.'],['Handmade with love','Every product is handcrafted with patience and care.'],['Custom cakes','From birthdays to weddings, we create cakes just for you.'],['On-time delivery','Careful preparation and dependable delivery for your moments.'],['Quality you trust','Quality and hygiene remain at the heart of every order.']];

export function withAboutDefaults(content={}){return{...defaults,...content,stats:defaults.stats.map((item,index)=>({...item,...content.stats?.[index]})),reasons:reasonDefaults.map(([title,text],index)=>({title,text,...content.reasons?.[index]}))}}

export default function AboutContentEditor({value,onChange}){
  const content=withAboutDefaults(value),[uploading,setUploading]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(''),[saved,setSaved]=useState(''),[categories,setCategories]=useState([]);
  useEffect(()=>{fetch(`${API}/main-categories`,{cache:'no-store'}).then(response=>response.json()).then(data=>setCategories((data.mainCategories||[]).filter(item=>item.isActive!==false))).catch(()=>{})},[]);
  const set=(key,next)=>onChange({...content,[key]:next});
  const item=(group,index,key,next)=>set(group,content[group].map((entry,itemIndex)=>itemIndex===index?{...entry,[key]:next}:entry));
  async function upload(key,file){if(!file)return;setUploading(key);setError('');try{const body=new FormData();body.append('media',file);body.append('folder','about');const response=await fetch(`${API}/admin/config/upload-media`,{method:'POST',headers:{Authorization:`Bearer ${localStorage.getItem('mnb_admin_token')}`},body});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Upload failed');set(key,data.url)}catch(uploadError){setError(uploadError.message)}finally{setUploading('')}}
  async function uploadCreation(slug,file){if(!file)return;const uploadKey=`creation-${slug}`;setUploading(uploadKey);setError('');try{const body=new FormData();body.append('media',file);body.append('folder','about-creations');const response=await fetch(`${API}/admin/config/upload-media`,{method:'POST',headers:{Authorization:`Bearer ${localStorage.getItem('mnb_admin_token')}`},body});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Upload failed');set('creationImages',{...(content.creationImages||{}),[slug]:data.url})}catch(uploadError){setError(uploadError.message)}finally{setUploading('')}}
  async function saveSection(section){setSaving(section);setSaved('');setError('');try{const response=await fetch(`${API}/admin/config`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('mnb_admin_token')}`},body:JSON.stringify({aboutContent:content})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Section save failed');setSaved(section)}catch(saveError){setError(saveError.message)}finally{setSaving('')}}
  const saveButton=(section,label)=><div className="about-section-save"><span>{saved===section?'Section saved successfully.':''}</span><button type="button" disabled={Boolean(saving)} onClick={()=>saveSection(section)}>{saving===section?<LoaderCircle className="spin" size={14}/>:null}{saving===section?'Saving...':`Save ${label}`}</button></div>;
  const media=(key,label)=><label className="about-admin-media">{label}<div>{content[key]?<img src={content[key]} alt=""/>:<span><Image size={22}/> No image</span>}<input type="file" accept="image/*" onChange={event=>upload(key,event.target.files?.[0])}/><button type="button" disabled={uploading===key} onClick={event=>event.currentTarget.previousElementSibling.click()}>{uploading===key?<LoaderCircle className="spin" size={14}/>:<Image size={14}/>} {uploading===key?'Uploading...':'Change image'}</button></div></label>;
  return <div className="about-admin-editor">
    <fieldset><legend>About Hero</legend><p className="config-help">Top section customers see first.</p><div className="about-admin-split"><div className="config-grid"><label>Small heading<input value={content.heroEyebrow} onChange={e=>set('heroEyebrow',e.target.value)}/></label><label>Hero title<input value={content.heroTitle} onChange={e=>set('heroTitle',e.target.value)}/></label><label className="wide">Description<textarea value={content.heroDescription} onChange={e=>set('heroDescription',e.target.value)}/></label></div>{media('heroImage','Hero image')}</div>{saveButton('hero','Hero')}</fieldset>
    <fieldset><legend>Our Story Section</legend><p className="config-help">The story card below the hero.</p><div className="about-admin-split"><div className="config-grid"><label>Small heading<input value={content.storyKicker} onChange={e=>set('storyKicker',e.target.value)}/></label><label>Image label<input value={content.storyImageLabel} onChange={e=>set('storyImageLabel',e.target.value)}/></label><label className="wide">Title<input value={content.storyTitle} onChange={e=>set('storyTitle',e.target.value)}/></label><label className="wide">Main story<textarea value={content.storyText} onChange={e=>set('storyText',e.target.value)}/></label><label className="wide">Closing text<textarea value={content.storyExtra} onChange={e=>set('storyExtra',e.target.value)}/></label></div>{media('storyImage','Story image')}</div>{saveButton('story','Story')}</fieldset>
    <fieldset><legend>Why Choose Us</legend><div className="config-grid"><label>Small heading<input value={content.reasonsKicker} onChange={e=>set('reasonsKicker',e.target.value)}/></label><label>Section title<input value={content.reasonsTitle} onChange={e=>set('reasonsTitle',e.target.value)}/></label></div><div className="about-admin-items">{content.reasons.map((reason,index)=><article key={index}><b>Feature {index+1}</b><input value={reason.title} onChange={e=>item('reasons',index,'title',e.target.value)}/><textarea value={reason.text} onChange={e=>item('reasons',index,'text',e.target.value)}/></article>)}</div>{saveButton('features','Features')}</fieldset>
    <fieldset><legend>Our Creations</legend><div className="config-grid"><label>Small heading<input value={content.creationKicker} onChange={e=>set('creationKicker',e.target.value)}/></label><label>Section title<input value={content.creationTitle} onChange={e=>set('creationTitle',e.target.value)}/></label><label className="wide">Button text<input value={content.creationButton} onChange={e=>set('creationButton',e.target.value)}/></label></div><p className="config-help about-admin-note">Main categories automatically appear here. Upload a separate card image for each category.</p><div className="about-creation-admin-grid">{categories.map(category=>{const uploadKey=`creation-${category.slug}`,image=content.creationImages?.[category.slug];return <article key={category._id||category.slug}><div>{image?<img src={image} alt=""/>:<span><Image size={20}/> No custom image</span>}</div><b>{category.name}</b><input id={`about-${uploadKey}`} type="file" accept="image/*" onChange={event=>uploadCreation(category.slug,event.target.files?.[0])}/><button type="button" disabled={uploading===uploadKey} onClick={()=>document.getElementById(`about-${uploadKey}`)?.click()}>{uploading===uploadKey?<LoaderCircle className="spin" size={13}/>:<Image size={13}/>} {uploading===uploadKey?'Uploading...':'Change image'}</button></article>})}</div>{saveButton('creations','Creations')}</fieldset>
    <fieldset><legend>Numbers Section</legend><div className="config-grid"><label>Small heading<input value={content.numbersKicker} onChange={e=>set('numbersKicker',e.target.value)}/></label><label>Section title<input value={content.numbersTitle} onChange={e=>set('numbersTitle',e.target.value)}/></label></div><div className="about-admin-items stats">{content.stats.map((stat,index)=><article key={index}><b>Number {index+1}</b><input value={stat.value} onChange={e=>item('stats',index,'value',e.target.value)}/><input value={stat.label} onChange={e=>item('stats',index,'label',e.target.value)}/></article>)}</div>{saveButton('numbers','Numbers')}</fieldset>
    {error&&<p className="hero-upload-error">{error}</p>}
  </div>
}
