import { LoaderCircle, MapPin, Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';

const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
const branchDefaults=[
  {name:'Afandi Town Hyderabad Branch',address:'My New Bakery - Afandi Town, Hyderabad, Sindh 17000, Pakistan',longitude:68.373,latitude:25.397},
  {name:'Auto Bahn Rd Hyderabad Branch',address:'Auto Bahn Road, opposite Unique Shopping Mall and Apartments, Latifabad Unit 2, Hyderabad, Sindh 71000, Pakistan',longitude:68.357,latitude:25.365},
  {name:'Bhurgari Rd Hyderabad Branch',address:'My New Bakery - Bhurgari Rd, Heerabad, Hyderabad, Sindh, Pakistan',longitude:68.368,latitude:25.401},
  {name:'Qasimabad Hyderabad Branch',address:'Plot # 9 Indus Gas Colony, Main Qasimabad Rd, Qasimabad, Hyderabad, Sindh 71000, Pakistan',longitude:68.337,latitude:25.382},
  {name:'Thandi Sarak Hyderabad Branch',address:'My New Bakery - Thandi Sarak, Hyderabad, Sindh 71500, Pakistan',longitude:68.371,latitude:25.378}
];
const defaults={eyebrow:'MY NEW BAKERY',title:'Contact us',introduction:"We'd love to hear from you. Whether you have a question, need help with an order, or want to discuss a custom cake, our team is here to help.",phone:'+92 300 0000000',whatsapp:'+92 300 0000000',email:'hello@mynewbakery.pk',address:'Hyderabad, Sindh, Pakistan',openingHours:'Mon – Sun: 10:00 AM – 9:00 PM',formKicker:'GET IN TOUCH',formTitle:'Send us a message',formDescription:'Tell us how we can help. Our bakery team will get back to you as soon as possible.',formButton:'Send Message',branches:branchDefaults};
export const withContactDefaults=(value={})=>({...defaults,...value,branches:Array.isArray(value.branches)&&value.branches.length?value.branches:branchDefaults});

export default function ContactContentEditor({value,onChange}){
  const content=withContactDefaults(value),[saving,setSaving]=useState(''),[saved,setSaved]=useState(''),[error,setError]=useState('');
  const set=(key,next)=>onChange({...content,[key]:next});
  const setBranch=(index,key,next)=>set('branches',content.branches.map((branch,itemIndex)=>itemIndex===index?{...branch,[key]:key==='longitude'||key==='latitude'?(next===''?'':Number(next)):next}:branch));
  const addBranch=()=>{const offset=content.branches.length*.001;set('branches',[...content.branches,{name:'New Hyderabad Branch',address:'Hyderabad, Sindh, Pakistan',longitude:Number((68.3578+offset).toFixed(6)),latitude:Number((25.396+offset).toFixed(6))}]);window.setTimeout(()=>document.querySelector('.contact-branch-editor article:last-child')?.scrollIntoView({behavior:'smooth',block:'center'}),50)};
  const removeBranch=index=>{if(window.confirm('Remove this branch location?'))set('branches',content.branches.filter((_,itemIndex)=>itemIndex!==index))};
  async function saveSection(section){setSaving(section);setSaved('');setError('');try{if(section==='branches'&&content.branches.some(branch=>!branch.name.trim()||!branch.address.trim()||branch.longitude===''||branch.latitude===''||!Number.isFinite(Number(branch.longitude))||!Number.isFinite(Number(branch.latitude))))throw new Error('Complete the branch name, address, longitude and latitude before saving.');const response=await fetch(`${API}/admin/config`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('mnb_admin_token')}`},body:JSON.stringify({contactContent:content})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Contact section save failed');setSaved(section)}catch(saveError){setError(saveError.message)}finally{setSaving('')}}
  const saveButton=(section,label)=><div className="about-section-save"><span>{saved===section?'Section saved successfully.':''}</span><button type="button" disabled={Boolean(saving)} onClick={()=>saveSection(section)}>{saving===section&&<LoaderCircle className="spin" size={14}/>} {saving===section?'Saving...':`Save ${label}`}</button></div>;
  return <div className="contact-admin-editor">
    <fieldset><legend>Contact Page Introduction</legend><p className="config-help">Heading and introduction displayed beside the globe.</p><div className="config-grid"><label>Small heading<input value={content.eyebrow} onChange={event=>set('eyebrow',event.target.value)}/></label><label>Page title<input value={content.title} onChange={event=>set('title',event.target.value)}/></label><label className="wide">Introduction<textarea value={content.introduction} onChange={event=>set('introduction',event.target.value)}/></label></div>{saveButton('intro','Introduction')}</fieldset>
    <fieldset><legend>Contact Details</legend><p className="config-help">These details appear on the left side of the Contact page.</p><div className="config-grid"><label>Phone<input value={content.phone} onChange={event=>set('phone',event.target.value)}/></label><label>WhatsApp<input value={content.whatsapp} onChange={event=>set('whatsapp',event.target.value)}/></label><label>Email<input type="email" value={content.email} onChange={event=>set('email',event.target.value)}/></label><label>Opening hours<input value={content.openingHours} onChange={event=>set('openingHours',event.target.value)}/></label><label className="wide">Displayed address<input value={content.address} onChange={event=>set('address',event.target.value)}/></label></div>{saveButton('details','Contact Details')}</fieldset>
    <fieldset><legend>Globe Branch Locations</legend><div className="branch-section-heading"><p className="config-help">Each saved branch appears as a pin on the globe. Latitude and longitude are the branch's exact map coordinates.</p><button type="button" onClick={addBranch}><Plus size={15}/> Add Branch Location</button></div><div className="contact-branch-editor">{content.branches.map((branch,index)=><article key={index}><header><span><MapPin size={15}/></span><strong>Branch {index+1}</strong><button type="button" className="branch-delete" onClick={()=>removeBranch(index)} title="Delete branch"><Trash2 size={14}/> Delete</button></header><label>Branch name<input required value={branch.name} onChange={event=>setBranch(index,'name',event.target.value)}/></label><label>Full address<textarea required value={branch.address} onChange={event=>setBranch(index,'address',event.target.value)}/></label><div><label>Longitude<input required type="number" step="0.000001" placeholder="68.357800" value={branch.longitude} onChange={event=>setBranch(index,'longitude',event.target.value)}/></label><label>Latitude<input required type="number" step="0.000001" placeholder="25.396000" value={branch.latitude} onChange={event=>setBranch(index,'latitude',event.target.value)}/></label></div></article>)}</div>{saveButton('branches','Branch Locations')}</fieldset>
    <fieldset><legend>Message Form Section</legend><p className="config-help">Text shown beside the customer contact form.</p><div className="config-grid"><label>Small heading<input value={content.formKicker} onChange={event=>set('formKicker',event.target.value)}/></label><label>Section title<input value={content.formTitle} onChange={event=>set('formTitle',event.target.value)}/></label><label className="wide">Description<textarea value={content.formDescription} onChange={event=>set('formDescription',event.target.value)}/></label><label className="wide">Button text<input value={content.formButton} onChange={event=>set('formButton',event.target.value)}/></label></div>{saveButton('form','Message Form')}</fieldset>
    {error&&<p className="hero-upload-error">{error}</p>}
  </div>;
}
