import { useEffect, useMemo, useState } from 'react';
import { Banknote, CheckCircle2, Clock3, FileText, Search, XCircle } from 'lucide-react';
import { printOrders } from '../orders/OrdersAdmin.jsx';

const money=value=>`Rs. ${(Number(value)||0).toLocaleString()}`;
const label=value=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,character=>character.toUpperCase());
const itemImage=item=>{const image=item?.image||item?.product?.images?.[0]||'';return image&&!/^(https?:|data:|blob:)/i.test(image)?`http://localhost:5000${image.startsWith('/')?'':'/'}${image}`:image};

export default function PaymentsManager({orders=[],patch}){
  const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[pageSize,setPageSize]=useState(5),[page,setPage]=useState(1),[selected,setSelected]=useState('');
  const transactions=useMemo(()=>orders.filter(order=>order.orderStatus!=='cancelled'),[orders]);
  const summary=useMemo(()=>['pending','paid','failed'].map(paymentStatus=>{const matching=transactions.filter(order=>order.paymentStatus===paymentStatus);return{status:paymentStatus,count:matching.length,total:matching.reduce((sum,order)=>sum+(Number(order.total)||0),0)}}),[transactions]);
  const filtered=useMemo(()=>transactions.filter(order=>(status==='all'||order.paymentStatus===status)&&`${order.orderNumber} ${order.customer?.name||''} ${order.customer?.email||''} ${order.phone||''} ${order.paymentMethod||''}`.toLowerCase().includes(query.trim().toLowerCase())),[transactions,status,query]);
  const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),shown=filtered.slice((page-1)*pageSize,page*pageSize),selectedOrder=orders.find(order=>order._id===selected);
  useEffect(()=>setPage(1),[query,status,pageSize]);useEffect(()=>setPage(current=>Math.min(current,pages)),[pages]);
  const icons={pending:Clock3,paid:CheckCircle2,failed:XCircle};
  return <div className="payments-manager"><div className="payment-summary">{summary.map(item=>{const Icon=icons[item.status];return <article className={item.status} key={item.status}><span><Icon size={22}/></span><div><small>{label(item.status)} Payments</small><strong>{money(item.total)}</strong><p>{item.count} transaction{item.count===1?'':'s'}</p></div></article>})}</div>
    <section className="category-manager payment-panel"><div className="category-heading"><div><p>PAYMENT MANAGEMENT</p><h2>Transactions <span>{filtered.length}</span></h2></div><button disabled={!selectedOrder} onClick={()=>printOrders([selectedOrder])}><FileText size={16}/> Print Invoice</button></div>
      <div className="payment-toolbar"><label><Search size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search order or customer..."/></label><select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All Payment Statuses</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="failed">Failed</option></select><select value={pageSize} onChange={event=>setPageSize(Number(event.target.value))}><option value="5">5 per page</option><option value="10">10 per page</option></select></div>
      <div className="table-wrap"><table className="payments-table"><colgroup><col className="col-select"/><col className="col-image"/><col className="col-product"/><col className="col-order"/><col className="col-customer"/><col className="col-amount"/><col className="col-method"/><col className="col-status"/><col className="col-date"/></colgroup><thead><tr><th className="payment-select-column">Select</th><th className="payment-image-column">Image</th><th>Product</th><th>Order</th><th>Customer</th><th>Amount</th><th>Method</th><th>Payment Status</th><th>Paid Date</th></tr></thead><tbody>{shown.map(order=>{const firstItem=order.items?.[0],image=itemImage(firstItem);return <tr className={selected===order._id?'selected':''} key={order._id} onClick={()=>setSelected(order._id)}><td className="payment-select-column"><input aria-label={`Select ${order.orderNumber}`} type="radio" name="invoice-order" checked={selected===order._id} onChange={()=>setSelected(order._id)}/></td><td className="payment-image-column">{image?<img className="payment-image" src={image} alt={firstItem?.name||'Product'}/>:<span className="payment-image empty">No image</span>}</td><td><div className="payment-product-names">{(order.items||[]).map((item,index)=><div key={`${item.name}-${index}`}><b>{item.name||item.product?.name||'Product'}</b><small>{item.quantity||1} × {item.size||'Standard'}</small></div>)}</div></td><td><b>{order.orderNumber}</b><small>{new Date(order.createdAt).toLocaleDateString('en-PK')}</small></td><td><b>{order.customer?.name||'Customer'}</b><small>{order.customer?.email}<br/>{order.phone}</small></td><td><b>{money(order.total)}</b></td><td><span className="payment-method">{label(order.paymentMethod)}</span></td><td><select className={`payment-status-select ${order.paymentStatus}`} value={order.paymentStatus} onClick={event=>event.stopPropagation()} onChange={event=>patch(order._id,{paymentStatus:event.target.value})}>{['pending','paid','failed'].map(value=><option key={value} value={value}>{label(value)}</option>)}</select></td><td>{order.paymentStatus==='paid'?new Date(order.updatedAt||order.createdAt).toLocaleString('en-PK',{dateStyle:'medium',timeStyle:'short'}):'—'}</td></tr>})}{!shown.length&&<tr><td colSpan="9" className="payment-empty">No matching payments found.</td></tr>}</tbody></table></div>
      <footer className="payment-pagination"><span>Showing {filtered.length?(page-1)*pageSize+1:0} to {Math.min(page*pageSize,filtered.length)} of {filtered.length} transactions</span><div><button className="secondary" disabled={page<=1} onClick={()=>setPage(current=>Math.max(1,current-1))}>Previous</button>{Array.from({length:pages},(_,index)=><button className={page===index+1?'current':''} key={index} onClick={()=>setPage(index+1)}>{index+1}</button>)}<button className="secondary" disabled={page>=pages} onClick={()=>setPage(current=>Math.min(pages,current+1))}>Next</button></div></footer>
    </section>
  </div>;
}
