import User from '../models/User.js';
import { generateToken } from '../utils/generateToken.js';
import crypto from 'crypto';
import { sendPasswordResetCode } from '../utils/sendEmail.js';
export async function register(req,res,next){try{const {name,email,password,phone}=req.body;if(await User.findOne({email}))return res.status(409).json({message:'Email already registered'});const user=await User.create({name,email,password,phone});res.status(201).json({user:{id:user._id,name:user.name,email:user.email,phone:user.phone,address:user.address,role:user.role,isVip:user.isVip,isActive:user.isActive},token:generateToken(user)})}catch(e){next(e)}}
export async function login(req,res,next){try{const identifier=String(req.body.identifier||req.body.email||'').trim(),password=String(req.body.password||'');const escaped=identifier.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const candidates=await User.find({$or:[{email:identifier.toLowerCase()},{name:{$regex:`^${escaped}$`,$options:'i'}}]}).select('+password');let user=null;for(const candidate of candidates){if(await candidate.comparePassword(password)){user=candidate;break}}if(!user)return res.status(401).json({message:'Invalid username/email or password'});if(user.isActive===false)return res.status(403).json({message:'This account is inactive. Please contact the bakery.'});res.json({user:{id:user._id,name:user.name,email:user.email,phone:user.phone,address:user.address,role:user.role,isVip:user.isVip,isActive:user.isActive},token:generateToken(user)})}catch(e){next(e)}}
export const me=(req,res)=>res.json({user:req.user});
export async function forgotPassword(req,res,next){try{const email=String(req.body.email||'').trim().toLowerCase();const user=await User.findOne({email,role:'admin'}).select('+passwordResetCodeHash +passwordResetExpires');if(!user)return res.json({message:'If this admin email exists, a reset code has been sent.'});const code=String(crypto.randomInt(100000,1000000));user.passwordResetCodeHash=crypto.createHash('sha256').update(code).digest('hex');user.passwordResetExpires=new Date(Date.now()+10*60*1000);await user.save({validateModifiedOnly:true});try{await sendPasswordResetCode(user.email,code)}catch(error){user.passwordResetCodeHash=undefined;user.passwordResetExpires=undefined;await user.save({validateModifiedOnly:true});return next(error)}res.json({message:'Reset code sent to your account email. It expires in 10 minutes.'})}catch(e){next(e)}}
export async function resetPassword(req,res,next){try{const email=String(req.body.email||'').trim().toLowerCase(),code=String(req.body.code||'').trim(),newPassword=String(req.body.newPassword||'');if(!email||!code||!newPassword)return res.status(400).json({message:'Email, reset code and new password are required'});if(newPassword.length<8)return res.status(400).json({message:'New password must be at least 8 characters'});const codeHash=crypto.createHash('sha256').update(code).digest('hex');const user=await User.findOne({email,role:'admin',passwordResetCodeHash:codeHash,passwordResetExpires:{$gt:new Date()}}).select('+password +passwordResetCodeHash +passwordResetExpires');if(!user)return res.status(400).json({message:'Reset code is invalid or expired'});user.password=newPassword;user.passwordResetCodeHash=undefined;user.passwordResetExpires=undefined;await user.save();res.json({message:'Password reset successfully. You can now log in.'})}catch(e){next(e)}}
