import Product from '../models/Product.js';
import StockMovement from '../models/StockMovement.js';
import { uploadImage } from '../config/cloudinary.js';
export async function listProducts(req,res,next){try{const isAdmin=req.user?.role==='admin';const filter=isAdmin?{}:{isActive:true,archived:{$ne:true}};if(req.query.type)filter.type=req.query.type;if(req.query.category)filter.category=req.query.category;const products=await Product.find(filter).populate('category','name slug').sort('-createdAt');res.json({products})}catch(e){next(e)}}
export async function getProduct(req,res,next){try{const product=await Product.findOne({slug:req.params.slug,isActive:true}).populate('category');if(!product)return res.status(404).json({message:'Product not found'});res.json({product})}catch(e){next(e)}}
export async function createProduct(req,res,next){try{res.status(201).json({product:await Product.create(req.body)})}catch(e){next(e)}}
export async function updateProduct(req,res,next){try{const product=await Product.findByIdAndUpdate(req.params.id,req.body,{returnDocument:'after',runValidators:true});if(!product)return res.status(404).json({message:'Product not found'});if(product.stock>product.lowStockThreshold&&product.lowStockNotificationSeenAt){product.lowStockNotificationSeenAt=undefined;await product.save()}res.json({product})}catch(e){next(e)}}
export async function deleteProduct(req,res,next){try{const product=await Product.findByIdAndDelete(req.params.id);if(!product)return res.status(404).json({message:'Product not found'});res.json({message:'Product permanently deleted'})}catch(e){next(e)}}
export async function adjustStock(req,res,next){try{const product=await Product.findById(req.params.id);if(!product)return res.status(404).json({message:'Product not found'});const amount=Number(req.body.amount)||0,before=product.stock;product.stock=Math.max(0,product.stock+amount);const changed=Math.abs(product.stock-before);if(product.stock>product.lowStockThreshold)product.lowStockNotificationSeenAt=undefined;await product.save();if(changed)await StockMovement.create({product:product._id,type:product.stock>before?'restock':'manual_removal',quantity:changed,stockBefore:before,stockAfter:product.stock,note:req.body.note});res.json({product})}catch(e){next(e)}}
export async function listStockMovements(req,res,next){try{const movements=await StockMovement.find().populate('product','name').sort('-createdAt').limit(500);res.json({movements})}catch(e){next(e)}}
export async function uploadProductImage(req,res,next){try{if(!req.file)return res.status(400).json({message:'Please choose an image file'});const uploaded=await uploadImage(req.file.buffer,'my-new-bakery/products');res.status(201).json({image:uploaded.secure_url,publicId:uploaded.public_id})}catch(e){next(e)}}
