import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { Menu, Search, ShoppingBag, UserRound } from 'lucide-react';
import { useStore } from '../../context/StoreContext.jsx';
import DesktopNav from './DesktopNav.jsx';
import MobileNav from './MobileNav.jsx';
import { useSiteConfig } from '../../services/siteConfig.js';
export default function Navbar(){const {cart,user}=useStore();const config=useSiteConfig();const [open,setOpen]=useState(false);const [visible,setVisible]=useState(true);const lastScroll=useRef(0);const count=cart.reduce((sum,item)=>sum+item.quantity,0);const bakeryName=config.bakeryName||'My New Bakery';
useEffect(()=>{const onScroll=()=>{const current=window.scrollY;if(current<72||current<lastScroll.current)setVisible(true);else if(current>lastScroll.current)setVisible(false);lastScroll.current=current};window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);
useEffect(()=>{document.documentElement.style.setProperty('--site-nav-offset',(visible||open)?'5rem':'0px');return()=>document.documentElement.style.removeProperty('--site-nav-offset')},[visible,open]);
return <><header className={`sticky top-0 z-40 flex h-20 items-center justify-between border-b border-white/20 bg-[#2c0903]/62 px-5 shadow-[0_12px_32px_rgba(20,3,1,.3)] backdrop-blur-2xl transition-transform duration-300 md:px-[6vw] ${(visible||open)?'translate-y-0':'-translate-y-full'}`}><Link to="/" className="flex items-center gap-3 font-display text-xs leading-none tracking-[0.13em]"><img className="h-11 w-11 rounded-full border border-gold/70 object-cover" src={config.logo||'/images/logo/logo.jfif'} alt={bakeryName}/><span>{bakeryName}</span></Link><DesktopNav/><div className="flex items-center gap-1"><Link className="p-2" to="/search" aria-label="Search"><Search size={19}/></Link><Link className="relative hidden p-2 sm:block" to={user?'/profile':'/login'} aria-label={user?.isVip?'VIP account':'Account'}><UserRound size={19}/>{user?.isVip&&<b className="absolute -right-2 -top-1 rounded-full border border-[#2c0903] bg-gold px-1.5 py-0.5 text-[7px] font-black tracking-[.08em] text-bakery">VIP</b>}</Link><Link className="relative p-2" to="/cart" aria-label="Shopping bag"><ShoppingBag size={19}/>{count>0&&<b className="absolute -right-1 -top-1 grid h-4 w-4 place-items-center rounded-full bg-gold text-[9px] text-bakery">{count}</b>}</Link><button onClick={()=>setOpen(true)} className="p-2 lg:hidden" aria-label="Open menu"><Menu size={21}/></button></div></header>{open&&<MobileNav onClose={()=>setOpen(false)}/>}</>}
