import { useEffect, useMemo, useState } from 'react';
import { Search, Star } from 'lucide-react';

function Stars({value=0}){return <span className="admin-stars" aria-label={`${Number(value).toFixed(1)} out of 5 stars`}>{[0,1,2,3,4].map(index=>{const fill=Math.max(0,Math.min(1,Number(value)-index));return <span key={index}><Star size={18}/><i style={{width:`${fill*100}%`}}><Star size={18} fill="currentColor"/></i></span>})}<b>{Number(value).toFixed(1)}/5</b></span>}

export default function ReviewsManager({items=[],patch,remove}){
  const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[rating,setRating]=useState('all'),[pageSize,setPageSize]=useState(5),[page,setPage]=useState(1);
  const filtered=useMemo(()=>items.filter(item=>`${item.product?.name||''} ${item.customer?.name||''} ${item.customer?.email||''} ${item.comment||''}`.toLowerCase().includes(query.trim().toLowerCase())&&(status==='all'||item.status===status)&&(rating==='all'||Math.floor(Number(item.rating))===Number(rating))),[items,query,status,rating]);
  const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),shown=filtered.slice((page-1)*pageSize,page*pageSize);
  useEffect(()=>setPage(1),[query,status,rating,pageSize]);useEffect(()=>setPage(current=>Math.min(current,pages)),[pages]);
  const change=async(item,next)=>{if(item.status!==next)await patch(item._id,next)};
  const erase=async item=>{if(window.confirm(`Delete review for ${item.product?.name||'this product'}?`))await remove(item._id)};
  return <section className="category-manager reviews-panel"><div className="category-heading"><div><p>CUSTOMER FEEDBACK</p><h2>Reviews <span>{items.length}</span></h2></div></div>
    <div className="review-filters"><label><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cake, customer or review..."/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="approved">Approved</option><option value="pending">Pending</option><option value="hidden">Hidden</option></select><select value={rating} onChange={e=>setRating(e.target.value)}><option value="all">All ratings</option>{[5,4,3,2,1].map(x=><option value={x} key={x}>{x} star{x>1?'s':''}</option>)}</select><select value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}><option value="5">5 per page</option><option value="10">10 per page</option></select></div>
    <div className="review-table-scroll"><table className="review-data-table"><thead><tr><th>Review</th><th>Rating</th><th>Customer</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody>{shown.map(item=><tr key={item._id}><td><div className="review-product"><img src={item.product?.images?.[0]||''} alt=""/><div><b>{item.product?.name||'Removed product'}</b><p>{item.comment&&String(item.comment).toLowerCase()!=='nan'?item.comment:'No written comment.'}</p></div></div></td><td><Stars value={item.rating}/></td><td><div className="review-customer"><b>{item.customer?.name||'Customer'}</b><small>{item.customer?.email}</small></div></td><td><span className={`review-status ${item.status}`}>{item.status}</span></td><td><time>{new Date(item.createdAt).toLocaleDateString('en-PK',{day:'2-digit',month:'short',year:'numeric'})}<small>{new Date(item.createdAt).toLocaleTimeString('en-PK',{hour:'2-digit',minute:'2-digit'})}</small></time></td><td><div className="review-actions"><button disabled={item.status==='approved'} onClick={()=>change(item,'approved')}>Approve</button><button className="secondary" onClick={()=>change(item,item.status==='hidden'?'approved':'hidden')}>{item.status==='hidden'?'Show':'Hide'}</button><button className="danger" onClick={()=>erase(item)}>Delete</button></div></td></tr>)}{!shown.length&&<tr><td colSpan="6" className="review-empty">No matching reviews found.</td></tr>}</tbody></table></div>
    <footer className="review-pagination"><span>Showing {filtered.length?(page-1)*pageSize+1:0} to {Math.min(page*pageSize,filtered.length)} of {filtered.length} reviews</span><div><button type="button" className="secondary" disabled={page<=1} onClick={()=>setPage(current=>Math.max(1,current-1))}>Previous</button>{Array.from({length:pages},(_,index)=><button type="button" className={page===index+1?'current':''} onClick={()=>setPage(index+1)} key={index}>{index+1}</button>)}<button type="button" className="secondary" disabled={page>=pages} onClick={()=>setPage(current=>Math.min(pages,current+1))}>Next</button></div></footer>
  </section>;
}
